### ISSUE TITLE
`https://crest-lab.github.io/` returns 404 error

### ISSUE THREAD

**Issue by matterhorn103** [crest-lab/crest-docs#11]
Thought you might like a heads-up that while https://crest-lab.github.io/crest-docs works, https://crest-lab.github.io doesn't.

**Comment by pprcht** [comment]
That's because the site is hosted on GitHub pages and /crest-docs is the _project_ landing site (i.e., form this repository right here), while https://crest-lab.github.io/ is the _organization_ site, for which no repository exists.

**Comment by matterhorn103** [comment]
Ah I see. Still, might it not be worth redirecting?
